apiVersion: v1
kind: Pod
metadata:
  name: vm-pod
  namespace: default
  labels:
    app: vm-pod
spec:
  hostNetwork: true
  volumes:
  - name: vm-fs
    hostPath:
      path: /tmp/rancher/vm-fs
  - name: vm-image
    emptyDir: {}
  - name: vm-socket
    hostPath:
      path: /tmp/rancher/vm-socks
  - name: dev-kvm
    hostPath:
      path: /dev/kvm
  initContainers:
  - name: vm-tools
    image: llparse/vm-tools:0.0.1
    volumeMounts:
    - name: vm-fs
      mountPath: /vm-tools
  containers:
  - name: vm
    image: llparse/vm-centos:7.1
    command: ['/usr/bin/startvm']
    env:
    - name: IFACE
      value: ens33
    - name: MEMORY_MB
      value: "512"
    - name: CPUS
      value: "1"
    # Use downward API so we can uniquely name VNC socket
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    securityContext:
      privileged: true
    volumeMounts:
    - name: vm-image
      mountPath: /image
    - name: dev-kvm
      mountPath: /dev/kvm
    - name: vm-socket
      mountPath: /vm
    - name: vm-fs
      mountPath: /bin
      readOnly: true
      subPath: bin
    - name: vm-fs
      mountPath: /etc
      readOnly: true
      subPath: etc
    - name: vm-fs
      mountPath: /lib
      readOnly: true
      subPath: lib
    - name: vm-fs
      mountPath: /lib64
      readOnly: true
      subPath: lib64
    - name: vm-fs
      mountPath: /sbin
      readOnly: true
      subPath: sbin
    - name: vm-fs
      mountPath: /usr
      readOnly: true
      subPath: usr
    - name: vm-fs
      mountPath: /var
      readOnly: true
      subPath: var
---
# We use a different pod with isolated net namespace so we don't have to worry
# about port conflicts between multiple VM-pods on a node.
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: novnc-pod
  labels:
    app: novnc
    podname: vm-pod
spec:
  volumes:
  - name: vm-socket
    hostPath:
      path: /tmp/rancher/vm-socks
  - name: podinfo
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
  containers:
  - name: novnc
    image: llparse/novnc:0.0.1
    # TODO add TLS
    command: ['novnc']
    env:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: vm-socket
      mountPath: /vm
    - name: podinfo
      mountPath: /podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: novnc-pod
spec:
  ports:
  - name: novnc
    port: 6080
  selector:
    app: novnc
    podname: vm-pod
  type: NodePort
